# Generated by Django 4.2.4 on 2023-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Task',
                'ordering': ['title'],
            },
        ),
    ]
