# Generated by Django 4.2.4 on 2023-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(0, 'Null'), (1, 'High'), (2, 'Medium'), (3, 'Low')], max_length=1),
        ),
    ]
