# Generated by Django 4.2.4 on 2023-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Null'), (1, 'High'), (2, 'Medium'), (3, 'Low')], default=0),
        ),
    ]
