# Generated by Django 4.2.4 on 2023-10-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
    ]
