# Generated by Django 4.2.4 on 2023-10-06 09:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_task_options_task_order'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
