# Generated by Django 4.2.4 on 2023-10-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_alter_task_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
