# Generated by Django 4.2.4 on 2023-10-29 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0014_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 29, 10, 10, 53, 688142)),
            preserve_default=False,
        ),
    ]
